### ISSUE TITLE
php-sieve-manager seems to prevent software to run on shared hosting

### ISSUE THREAD

**Issue by torstenfabricius** [cypht-org/php-sieve-manager#1]
Dear @henrique-borba,
(cc. @marclaporte )

I am member of the community of the Tiki app, which uses a **Cypht** integration for our webmail feature.
Cypht uses **php-sieve-manager** for server side filtering. 
And php-sieve-manager requires the php extension **ext-sockets**.

Because ext-sockets is not available with my shared hosting provider (all-inkl.com), I discussed with their support what would be the reason. They told me that sockets would have to be installed and configured globally per server and customers sharing a server would be able to unintendedly interfere with each others configuration or data ... it would be a security issue to provide sockets for shared servers. So it would be likely rare that shared hosting provider would provide sockets and if yes it would not be recommended to use them.

This is a problem for us - at least for me ;-) .

What is the reason, that php-sieve-manager requires ext-sockets and would it be possible to make server side filtering working (similar fast and stable) without ext-sockets?

I'd appreciate any feedback and the opportunity to discuss the issue with you.

Following the error message of the (shared hosting) servers command line when trying to install the composer dependencies:

`
Local PHP version 74 >= to required PHP version 74 - good
You are already using the latest available Composer version 2.4.1 (2.x channel).
....

  Problem 1
    - henrique-borba/php-sieve-manager is locked to version dev-master and an update of this package was not requested.
    - henrique-borba/php-sieve-manager dev-master requires ext-sockets * -> it is missing from your system. Install or enable PHP's sockets extension.

  Problem 2
    - henrique-borba/php-sieve-manager dev-master requires ext-sockets * -> it is missing from your system. Install or enable PHP's sockets extension.
    - jason-munro/cypht dev-master requires henrique-borba/php-sieve-manager dev-master -> satisfiable by henrique-borba/php-sieve-manager[dev-master].
    - jason-munro/cypht is locked to version dev-master and an update of this package was not requested.
`

Best regards,
Torsten

**Comment by marclaporte** [comment]
Feedback from @neildarlow in the chat: https://gitter.im/cypht-org/community?at=6303f3f0999499629302f16a

**Comment by marclaporte** [comment]
@henrique-borba and I discussed today: We'll make a change in Cypht so Sieve support is optional.

**Comment by marclaporte** [comment]
Solved: https://github.com/henrique-borba/php-sieve-manager/commit/e5c87076476e4d23c59f035946ae10e1e907a7e5
