### ISSUE TITLE
Review redirect vs forward

### ISSUE THREAD

**Issue by marclaporte** [cypht-org/php-sieve-manager#20]
We now have: https://github.com/cypht-org/php-sieve-manager/blob/master/src/Filters/Actions/RedirectFilterAction.php

So email is redirected (forwarded) and a copy is not kept in the account.

If supported by Sieve, let's also add a way to forward the email, but keep a copy on the server. So we end up with 2 copies of the email.

After doing in the lib, please add to Cypht :-)

**Comment by Shadow243** [comment]
> We now have: https://github.com/cypht-org/php-sieve-manager/blob/master/src/Filters/Actions/RedirectFilterAction.php
> 
> So email is redirected (forwarded) and a copy is not kept in the account.
> 
> If supported by Sieve, let's also add a way to forward the email, but keep a copy on the server. So we end up with 2 copies of the email.
> 
> After doing in the lib, please add to Cypht :-)

this seems to be already supported with the `copy` parameter: [RedirectFilterAction.php#L17](https://github.com/cypht-org/php-sieve-manager/blob/master/src/Filters/Actions/RedirectFilterAction.php#L17). I'm testing

**Comment by Shadow243** [comment]
> > We now have: https://github.com/cypht-org/php-sieve-manager/blob/master/src/Filters/Actions/RedirectFilterAction.php
> > So email is redirected (forwarded) and a copy is not kept in the account.
> > If supported by Sieve, let's also add a way to forward the email, but keep a copy on the server. So we end up with 2 copies of the email.
> > After doing in the lib, please add to Cypht :-)
> 
> this seems to be already supported with the `copy` parameter: [RedirectFilterAction.php#L17](https://github.com/cypht-org/php-sieve-manager/blob/master/src/Filters/Actions/RedirectFilterAction.php#L17). I'm testing

parameter `copy` is not supported by many servers, we are combining `redirect` with `keep` soo every server will support.

**Comment by Shadow243** [comment]
Complete and tested with @josaphatim
